### ISSUE TITLE
Source for ncnn-sys crate

### ISSUE THREAD

**Issue by chemicstry** [darkskygit/waifu2x.rs#1]
Hi,

I'm having trouble finding the source for `ncnn-sys` crate. The [crates.io package](https://crates.io/crates/ncnn-sys) links to this repository, but it only contains the waifu2x code.

**Comment by darkskygit** [comment]
source code of ncnn-sys are here: https://github.com/darkskygit/waifu2x.rs/tree/ncnn-sys

**Comment by chemicstry** [comment]
Ah sorry, it's a bit unusual to have separate projects as branches
