### ISSUE TITLE
Scale higher than 2 results in bad output

### ISSUE THREAD

**Issue by MolotovCherry** [darkskygit/waifu2x.rs#2]
With any scale higher than 2, it seems to result in bad output

Tilesize 8, scale 8 (though tilesize doesn't seem to change anything, so it can be ignored)
Using Win11

Scale 2 works perfectly fine however

![test](https://github.com/darkskygit/waifu2x.rs/assets/13651622/71a101e3-6159-4098-b460-811a0820143a)

![output](https://github.com/darkskygit/waifu2x.rs/assets/13651622/286c543d-8625-4499-85b5-65fbef0de6fd)

**Comment by darkskygit** [comment]
waifu2x only has native 2x scale model, if scale > 2, some implementations will help you scale the scaled graph multiple times to make it match your desired scale size
this feature not implemented in this library, i think it is not hard to implement, but since i don't have a windows computer to use recently, if you can provide a pr, I would welcome it

**Comment by MolotovCherry** [comment]
Indeed! I took a look at that official c++ code and that indeed appears to be what's going on. I'll hack together a PR, but it appears I will have to change the signature of `Waifu2x::new()` to return a result, as the only valid sizes for scaling are 1,2,4,8,16,32. (There might also be some invalid tilesize settings, though I don't want to implement the error handling for that atm)

Is this okay? Or perhaps something like an enum is better (and I could make a `from_num() -> Result<Self, Error>` function for it to convert to the enum from a number, and the opposite `to_num()` to convert back for the code)

Let me know your preferences on the implementation :)

**Comment by darkskygit** [comment]
please feel free to modify the signature.
the current implementation does not check the parameters, i think that also can be implemented in rust.

**Comment by darkskygit** [comment]
> as the only valid sizes for scaling are 1,2,4,8,16,32

i have found a method in some other implementations: when user provides an irregular scale value, the implementation can first scale to the nearest and larger than the value provided, and then reduce the image to the provided scale.
